### ISSUE TITLE
Android Basics: conditional-dice-roll-behavior

### ISSUE THREAD

**Issue by TecBrat** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#92] opened 2022-01-03 00:39 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-conditional-dice-roll-behavior?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-conditional-dice-roll-behavior#5

**In which task and step of the codelab can this issue be found?**
6 Summary

**Describe the problem**
The last section has this
When statement:

when (variable) {
    matches-value > execute-this-code
    matches-value > execute-this-code
    ...
}

I believe it should be this:
When statement:

when (variable) {
    matches-value -> execute-this-code
    matches-value -> execute-this-code
    ...
}

**Steps to reproduce?**
na

**Versions**
na

**Comment by and-rea** [comment] 2022-01-28 14:39
duplicate of #84

**Comment by osuleymanova** [comment] 2022-04-08 23:09
Duplicate of #83, #84, #87
@TecBrat 
Thank you for reporting this issue. It's already fixed and will be published soon.

**Closed by osuleymanova** 2022-04-08 23:09 UTC
