### ISSUE TITLE
Android Basics: conditional-dice-roll-behavior

### ISSUE THREAD

**Issue by noahcams** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#101] opened 2022-01-24 19:14 UTC
**URL of codelab**

**In which task and step of the codelab can this issue be found?**
Part 6: summary

**Describe the problem**
The syntax for the when statement is incorrect. ">" should be "->" for each condition.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by and-rea** [comment] 2022-01-28 14:40
duplicate of #84

**Comment by osuleymanova** [comment] 2022-04-08 23:10
Duplicate of #83, #87, #92

**Closed by osuleymanova** 2022-04-08 23:10 UTC
