### ISSUE TITLE
Android Basics: conditional-dice-roll-behavior

### ISSUE THREAD

**Issue by gustainMars** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#60] opened 2021-11-01 17:27 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-conditional-dice-roll-behavior?authuser=1&hl=pt&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%3Fauthuser%3D1%26hl%3Dpt%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-conditional-dice-roll-behavior#5

**In which task and step of the codelab can this issue be found?**
6. Resume

**Describe the problem**
On the when resume, it appears "matches-value **-&gt;**` *`execute-this-code`*" instead of matches-value **->**` *`execute-this-code`*

**Steps to reproduce?**
1. Go to link on URL of the codelab
2. Go to Step 6
3. See error on explanation of when structure

**Versions**
_Android Studio version:_  Don't apply
_API version of the emulator:_  Don't apply

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

![image](https://user-images.githubusercontent.com/37446244/139713766-b3650349-edfd-4116-9bd5-34d0ef472f64.png)

**Comment by osuleymanova** [comment] 2021-12-06 20:33
@gustainMars 
Thank you for reaching out to us. The issue is fixed and will be published soon:
when (variable) {
    matches-value -> execute-this-code
    matches-value -> execute-this-code
    …
}

**Comment by osuleymanova** [comment] 2021-12-06 20:34
Duplicate of #66, #67

**Closed by osuleymanova** 2021-12-06 20:33 UTC
