### ISSUE TITLE
Android Basics: create-dice-roller-app-with-button

### ISSUE THREAD

**Issue by Jono1954** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#21] opened 2021-05-07 13:57 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-create-dice-roller-app-with-button?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-create-dice-roller-app-with-button#3

**In which task and step of the codelab can this issue be found?**
Step 4 Introduction to Activities
Enable auto imports

**Describe the problem**
1. In Android Studio, open the settings by going to File > New Project Settings > Preferences for New Projects on macOS. In Windows go to File > Other Setting > Setting for New Projects... .

Not sure about the macOS menus but it seems the Windows menu sequence should be File >  New Projects Settings > Settings for New Projects

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 4.1.3
_API version of the emulator:_ 29

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment] 2021-12-02 01:53
Duplicate of #18, #19, #27

**Comment by osuleymanova** [comment] 2021-12-02 01:53
@Jono1954 
Thank you for reaching out to us. The issue is fixed and will be published soon.

**Closed by osuleymanova** 2021-12-02 01:53 UTC
