### ISSUE TITLE
Android Basics: conditional-dice-roll-behavior

### ISSUE THREAD

**Issue by martyna-g** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#118] opened 2022-04-04 11:04 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-conditional-dice-roll-behavior?authuser=1#5

**In which task and step of the codelab can this issue be found?**
Add conditional behavior in Kotlin; 6. Summary; When statement

**Describe the problem**
There should be '->' not '>' between branches and values in the when statement

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![when statement](https://user-images.githubusercontent.com/69039386/161530828-e49d6378-8b06-49f5-8447-d63f435a2e7f.png)

**Comment by osuleymanova** [comment] 2022-04-11 18:32
Duplicate of #83, #84, # 87, #101, #109, #114
 @martyna-g 
It's already handled. Thank you.

**Closed by osuleymanova** 2022-04-11 18:32 UTC
