### ISSUE TITLE
Android Basics: conditional-dice-roll-behavior

### ISSUE THREAD

**Issue by AntoineLyon** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#59] opened 2021-11-01 15:17 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-conditional-dice-roll-behavior?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-conditional-dice-roll-behavior#5

**In which task and step of the codelab can this issue be found?**
Summary

**Describe the problem**
in When condition recap, it shows "-&gt;" instead of "->"

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment] 2021-12-06 20:37
Duplicate of #60, #66, #67

**Comment by osuleymanova** [comment] 2021-12-06 20:37
@AntoineLyon 
Thank you for reaching out to us. The issue is fixed and will be published soon:
when (variable) {
    matches-value -> execute-this-code
    matches-value -> execute-this-code
    …
}

**Closed by osuleymanova** 2021-12-06 20:37 UTC
