### ISSUE TITLE
Android Basics: create-dice-roller-app-with-button

### ISSUE THREAD

**Issue by zunaidansari** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#27] opened 2021-05-27 16:14 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-create-dice-roller-app-with-button?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-create-dice-roller-app-with-button#3

**In which task and step of the codelab can this issue be found?**
**Enable auto imports**
 In Windows go to File > Other Setting > Setting for New Projects... .
**Describe the problem**
I follow the above-mentioned
![Screenshot (13)](https://user-images.githubusercontent.com/55325057/119860693-3860ba80-bf34-11eb-96c3-ef4310365d2d.png)
 process but that is not correct there is no such option as Other Setting in file, and also if I choose settings in the file and then go to other settings then there is no Setting new projects option, instead 3 options as Clang-Tidy, Clangd, Kotlin Compiler.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 4.2.1
_API version of the emulator:_ Android 10.0

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment] 2021-12-02 01:49
Duplicate of #18, #19

**Comment by osuleymanova** [comment] 2021-12-02 01:50
@zunaidansari 
Thank you for reaching out to us. The issue was mentioned earlier. It is fixed and will be published soon.

**Closed by osuleymanova** 2021-12-02 01:50 UTC
