### ISSUE TITLE
Android Basics: conditional-dice-roll-behavior

### ISSUE THREAD

**Issue by mayursojitra** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#87] opened 2021-12-22 07:28 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-conditional-dice-roll-behavior#5

**In which task and step of the codelab can this issue be found?**
In 6 Summary example of When statement.
when (variable) {
    matches-value > execute-this-code
    matches-value > execute-this-code
    ...
}

**Describe the problem**
matches-value > execute-this-code
In this above statement, there should be -> instead of >

**Comment by and-rea** [comment] 2022-01-28 14:38
duplicate of #84

**Comment by osuleymanova** [comment] 2022-04-08 23:08
Duplicate of #83, #84

**Closed by osuleymanova** 2022-04-08 23:08 UTC
