### ISSUE TITLE
Android Basics: conditional-dice-roll-behavior

### ISSUE THREAD

**Issue by guru-meditation-no42** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#114] opened 2022-02-22 05:14 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-conditional-dice-roll-behavior?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-conditional-dice-roll-behavior#5

**In which task and step of the codelab can this issue be found?**
Task 6 "Add conditional behavior in Kotlin", step "6. Summary"

**Describe the problem**
Example code for the "when" statement syntax is given as "matches-value > execute-this-code", when previous examples (and I believe correct syntax) use the '->' operator rather than '>'.  Using the '>' operator will not compile.

**Steps to reproduce?**
See URL given above and attached screenshot.

**Versions**
_Android Studio version:_  N/A
_API version of the emulator:_ N/A

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![Screenshot from 2022-02-21 21-07-22](https://user-images.githubusercontent.com/78309818/155067011-a2864bdb-e44b-4824-9abf-52b9fca21009.png)

**Comment by osuleymanova** [comment] 2022-04-08 23:17
Duplicate of #83, #84, #87, #92, #101, #109, #111, #113

**Closed by osuleymanova** 2022-04-08 23:17 UTC
