### ISSUE TITLE
Android Basics: conditional-dice-roll-behavior

### ISSUE THREAD

**Issue by Sajjad-Arjmand** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#111] opened 2022-02-13 18:38 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-conditional-dice-roll-behavior?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-conditional-dice-roll-behavior#5

**In which task and step of the codelab can this issue be found?**
step 6 - summary

**Describe the problem**
in the last paragraph,
general form of when statement is
`
when (variable) {
    matches-value > execute-this-code
    matches-value > execute-this-code
    ...
}
`
shouldn't that be like "matches-value -> execute-this-code" ?

**Comment by osuleymanova** [comment] 2022-04-08 23:12
Duplicate of #83, #84, #87, #92, #101, #109

**Comment by osuleymanova** [comment] 2022-04-08 23:13
@Sajjad-Arjmand 
Thank you for reaching out to us. The issue is fixed and will be published soon.

**Closed by osuleymanova** 2022-04-08 23:13 UTC
