### ISSUE TITLE
Android Basics: conditional-dice-roll-behavior

### ISSUE THREAD

**Issue by ali1958** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#109] opened 2022-01-31 21:04 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-conditional-dice-roll-behavior?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-conditional-dice-roll-behavior#5

**In which task and step of the codelab can this issue be found?**
Description for When statement

**Describe the problem**
It is written:
when (variable) {
    matches-value > execute-this-code
    matches-value > execute-this-code
    ...
}

The correct syntax must be with "->", not with ">".

**Comment by osuleymanova** [comment] 2022-04-08 23:11
Duplicate of #83, #84, #87, #92, #101

**Closed by osuleymanova** 2022-04-08 23:11 UTC
