### ISSUE TITLE
Android Basics: create-dice-roller-in-kotlin

### ISSUE THREAD

**Issue by Laura-Jacinto** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#69] opened 2021-11-13 22:57 UTC
**URL of codelab**https://developer.android.com/codelabs/basic-android-kotlin-training-create-dice-roller-in-kotlin?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-create-dice-roller-in-kotlin#2

**In which task and step of the codelab can this issue be found?**Create an instance of the Dice class

**Describe the problem**
The code not work. Error message is: 
![image](https://user-images.githubusercontent.com/93161818/141661391-9ee762a0-930b-4b5e-82f6-ddfa2e5d2206.png)

**Steps to reproduce?**
1. Go to...Playground de Kotlin
2. Click on...Run
3. See error...image

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/93161818/141661402-4dbc3cd4-6ec5-4014-8a18-2755600ccba7.png)

**Comment by osuleymanova** [comment] 2022-05-24 00:17
@Laura-Jacinto 
Thank you for reaching out to us and providing the screenshot with the error messages. 
Entering the code provided in your screenshot we've got the correct output. Please see the screenshot below:
![Screen Shot 2022-05-23 at 5 10 08 PM](https://user-images.githubusercontent.com/86437155/169923770-eaf41a7c-fc2a-41c0-90c4-3ec6e3d46b1e.png)
So the issue is closed as it won't reproducible.

**Closed by osuleymanova** 2022-05-24 00:17 UTC
