### ISSUE TITLE
Android Basics: create-dice-roller-in-kotlin

### ISSUE THREAD

**Issue by Lunarclipper** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#79] opened 2021-12-05 20:14 UTC
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
This is more of a grammar problem than a coding problem. Throughout this lesson the text keeps referring to a single die as "a dice". "Dice" is the plural form of the word, indicating two or more. The singular is "die". https://www.grammarly.com/blog/dice-die/

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment] 2021-12-07 20:28
Duplicate of #75

**Comment by osuleymanova** [comment] 2021-12-07 22:32
@Lunarclipper 
Thank you for your feedback. While it is true that the singular form of dice is "die", we decided that "dice" would have a more positive tone in the codelab compared to the word "die". And in some instances, people do casually use the word "dice" for singular form. Thank you again for the feedback and for taking our codelab. Hope it was a helpful learning experience!

**Closed by osuleymanova** 2021-12-07 22:32 UTC

**Comment by Lunarclipper** [comment] 2021-12-08 13:53
Thank you for your response and for explaining reasoning behind the choice
of words with me. This sounds well thought out to me.

Please extended my wishes for pleasant holidays to your team, may you and
yours enjoy whichever holidays you celebrate 😊
