### ISSUE TITLE
Android Basics: create-dice-roller-app-with-button

### ISSUE THREAD

**Issue by vlorax** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#15] opened 2021-03-31 16:05 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-create-dice-roller-app-with-button?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-create-dice-roller-app-with-button#10

**In which task and step of the codelab can this issue be found?**
Step 5

**Describe the problem**
Using the default AVD in Android Studio and running the App, Toast message will never display

**Steps to reproduce?**
1. Follow Steps to create Toast msg in codelab
2. Click the roll button
3. Toast will never display

**Versions**
_Android Studio version:_ 4.1.3
_API version of the emulator:_ 30

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment] 2021-12-02 01:00
@vlorax 
Thank you for reaching out to us. Could you clarify please what codelab you are concerning about? Please provide more details so we could help you.

**Comment by osuleymanova** [comment] 2022-04-11 19:34
@vlorax 
The issue is closed as no further clarification of it was provided.

**Closed by osuleymanova** 2022-04-11 19:34 UTC
