### ISSUE TITLE
Android Basics: conditional-dice-roll-behavior

### ISSUE THREAD

**Issue by dipanshuraj0** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#50] opened 2021-09-12 20:38 UTC
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by dipanshuraj0** [comment] 2021-09-12 20:39
Dice(6) not working
Unresolved reference

**Comment by osuleymanova** [comment] 2021-12-06 20:48
@dipanshuraj0 
Thank you for reaching out to us. Could you provide more details please?

**Comment by osuleymanova** [comment] 2022-04-08 23:20
@dipanshuraj0 
The issue is closed as no further clarification of it was provided.

**Closed by osuleymanova** 2022-04-08 23:20 UTC
