### ISSUE TITLE
Android Basics: DONE button missing - create-dice-roller-app-with-button

### ISSUE THREAD

**Issue by Raghu0203** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#8] opened 2021-02-10 14:36 UTC
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
After reaching the end of the codelab there is no continue button to move to the next section i,e we need to go back to the main page  in order to access the next section 

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment] 2021-12-01 01:13
@Raghu0203 
Thank you for reaching out to us. What OS are you using?

**Comment by osuleymanova** [comment] 2022-04-08 22:36
The issue is closed as no further clarification of it was provided.

**Closed by osuleymanova** 2022-04-08 22:36 UTC
Labels: question
