### ISSUE TITLE
Android Basics: conditional-dice-roll-behavior

### ISSUE THREAD

**Issue by RealOkabe** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#113] opened 2022-02-21 19:11 UTC
**URL of codelab**
https://developer.android.com/courses/android-basics-kotlin/unit-1

**In which task and step of the codelab can this issue be found?**
Summary of "Add conditional behavior in Kotlin"

**Describe the problem**
The syntax for using when seems to be incorrect
 This is the intended syntax from kotlinlang.org:
when (x) {
    1 -> print("x == 1")
    2 -> print("x == 2")
    else -> {
        print("x is neither 1 nor 2")
    }
}

This is the given syntax:
 when (variable) {
    matches-value > execute-this-code
    matches-value > execute-this-code
    ...
}

**Steps to reproduce?**
1. Go to... https://developer.android.com/courses/android-basics-kotlin/unit-1
2. Click on... Add a button to an app
3. Go to Summary
4. See error in the syntax given

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment] 2022-04-08 23:14
Duplicate of #83, #84, #87, #92, #101, #109, #111

**Comment by osuleymanova** [comment] 2022-04-08 23:15
@RealOkabe 
Thank you for reaching out to us. The issue is fixed and will be published soon
![Screen Shot 2022-04-08 at 4 03 42 PM](https://user-images.githubusercontent.com/86437155/162545318-a4e78c14-95f7-4132-ba10-c4037b9e5eb6.png)
.

**Closed by osuleymanova** 2022-04-08 23:15 UTC
