### ISSUE TITLE
Android Basics: create-dice-roller-in-kotlin

### ISSUE THREAD

**Issue by maeuza** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#97] opened 2022-01-21 05:58 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-create-dice-roller-in-kotlin?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-create-dice-roller-in-kotlin#5

**In which task and step of the codelab can this issue be found?**

The code

**Describe the problem**

Is it possible to simplify the code like this ?  

fun main()  {
    var sides = 6
    roll(sides)
     sides = 20
    roll(sides)
}
    fun roll(sides: Int) {
        println("Your ${sides} sided dice rolled ${(1..sides).random()}!")
    }
  
I know that it would not work with an instance, it is just a doubt that I have. thanks

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment] 2022-05-25 00:24
@maeuza 
Thank you for reaching out to us. The main focus of the codelab is not to provide the simplified version of the code but to teach the basics which you may adjust upon your desire. Your code is runnable but with different output. 
The issue is closed as won't fix.

**Closed by osuleymanova** 2022-05-25 00:24 UTC
