### ISSUE TITLE
Android Basics: conditional-dice-roll-behavior

### ISSUE THREAD

**Issue by RuslanBairashev** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#84] opened 2021-12-15 12:14 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-conditional-dice-roll-behavior?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-conditional-dice-roll-behavior#5

**In which task and step of the codelab can this issue be found?**
Add conditional behavior in Kotlin : 6 Summary

**Describe the problem**
text "matches-value > execute-this-code" should be "matches-value -> execute-this-code"
arrow instead of bigger

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by BlvckWQlf** [comment] 2022-01-29 22:35
Is this a solution or a problem? Cause it looks like it's giving instructions in the link.

**Comment by osuleymanova** [comment] 2022-04-08 23:07
Duplicate of #83 
@RuslanBairashev 
Thank you for reaching out to us. The issue is already handled.

**Closed by osuleymanova** 2022-04-08 23:07 UTC
Labels: duplicate
