### ISSUE TITLE
Android Basics: create-dice-roller-app-with-button

### ISSUE THREAD

**Issue by N0il** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#64] opened 2021-11-05 08:56 UTC
**https://developer.android.com/codelabs/basic-android-kotlin-training-create-dice-roller-app-with-button?authuser=5&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%3Fauthuser%3D5%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-create-dice-roller-app-with-button#3**

**Step 4: Introduction to Activities**

**On the section: Open MainActivity.kt file, the topic (app > java > com.example.digeroll > MainActivity.kt) has an typing error, it should be "com.example.diceroll" and not "com.example.digeroll"**

**Comment by osuleymanova** [comment] 2021-11-30 00:49
Duplicate of #61

**Closed** 2021-12-02 22:21 UTC
